# Generated by Django 4.2.4 on 2023-08-27 03:41

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MainPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PostInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('creation_time', models.DateTimeField(default=datetime.datetime.now)),
                ('last_edit_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='postinfo',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.userdata'),
        ),
        migrations.AddField(
            model_name='postinfo',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.community'),
        ),
        migrations.AddField(
            model_name='mainpost',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.postinfo'),
        ),
        migrations.AddField(
            model_name='commentpost',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.postinfo'),
        ),
        migrations.AddField(
            model_name='commentpost',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mainpost'),
        ),
    ]
