# Generated by Django 4.2.4 on 2023-08-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_userdata_username_alter_userdata_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='community',
            name='rules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='moderating',
            field=models.ManyToManyField(blank=True, related_name='moderating_set', to='main.community'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='community_set', to='main.community'),
        ),
    ]
