# Generated by Django 4.2.4 on 2023-08-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_community_description_community_rules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='user_set', to='main.community'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='moderating',
            field=models.ManyToManyField(blank=True, related_name='moderator_set', to='main.community'),
        ),
    ]
