# Generated by Django 4.2.4 on 2023-08-30 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_post_thread_remove_mainpost_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='comment_root',
            new_name='root_post',
        ),
    ]
