# Generated by Django 4.2.4 on 2023-08-30 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_comment_root_thread_root_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
