# Generated by Django 4.2.4 on 2023-08-30 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_community_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.post'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.community'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='root_post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.post'),
        ),
    ]
