# Generated by Django 4.2.4 on 2023-08-30 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_post_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.post'),
        ),
    ]
